name: Check Secret

on: [push, pull_request]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Secret Value
        run: echo "DATABASE_URL=$(echo $DATABASE_URL | base64)"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
