name: Check Secret

on: [push, pull_request]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check DATABASE_URL
        run: |
          if [[ "$DATABASE_URL" == *"localhost"* ]]; then
            echo "DATABASE_URL contains localhost"
          else
            echo "DATABASE_URL does not contain localhost"
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
